lenguajes = ["php", "java", "python"]
print("lenguaje seleccionado" + lenguajes[0])
print(lenguajes)
lenguajes.append("javascript")
print(lenguajes)
lenguajes.remove("php")
print(lenguajes)
lenguajes.pop()
print(lenguajes)
lenguajes.insert(1, "ruby")
print(lenguajes)
lenguajes.sort()
print(lenguajes)
lenguajes.reverse()
print(lenguajes)
print("El largo de la lista es: " + str(len(lenguajes)))
print(lenguajes[1:3])
